# Generated by Django 4.2.2 on 2024-05-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(default='', max_length=150)),
                ('latitude', models.CharField(default='', max_length=150)),
                ('device', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
